[tool.poetry]
name = "k5-tools"
version = "0.5"
description = ""
authors = ["hank9999 <hank9999@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pyserial = "^3.5"
ttkbootstrap = "^1.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
